spring:
  application:
    name: jsp_test
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  datasource:
    url: jdbc:mariadb://localhost:3306/testJSP
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: qlxkals